# Generated by Django 5.1 on 2024-09-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0003_alter_friendship_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
